//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGasNatural.Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GasNaturalEntities : DbContext
    {
        public GasNaturalEntities()
            : base("name=GasNaturalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAUSAS> CAUSAS { get; set; }
        public virtual DbSet<COMPONENTES> COMPONENTES { get; set; }
        public virtual DbSet<COMPROBANTE> COMPROBANTE { get; set; }
        public virtual DbSet<ETAPAS> ETAPAS { get; set; }
        public virtual DbSet<FALLOS> FALLOS { get; set; }
        public virtual DbSet<MONITOREO> MONITOREO { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PLANEACION> PLANEACION { get; set; }
        public virtual DbSet<RECIBO> RECIBO { get; set; }
        public virtual DbSet<RECORRIDO> RECORRIDO { get; set; }
        public virtual DbSet<SERVICIOS> SERVICIOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
