//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGasNatural.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANEACION
    {
        public int IdPlaneacion { get; set; }
        public int IdServicio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdPersonaCreacion { get; set; }
        public int IdPersonaModificacion { get; set; }
        public int IdEtapa { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual ETAPAS ETAPAS { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual PERSONA PERSONA1 { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
