//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGasNatural.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO
    {
        public int IdRecibo { get; set; }
        public decimal Monto { get; set; }
        public decimal Iva { get; set; }
        public byte[] FirmaTecnico { get; set; }
        public byte[] FirmaUsuario { get; set; }
        public int IdServicio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaImpresion { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
