//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGasNatural.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS()
        {
            this.COMPROBANTE = new HashSet<COMPROBANTE>();
            this.MONITOREO = new HashSet<MONITOREO>();
            this.PLANEACION = new HashSet<PLANEACION>();
            this.RECIBO = new HashSet<RECIBO>();
        }
    
        public int IdServicio { get; set; }
        public int IdPersonaTecnico { get; set; }
        public int IdPersonaCreacion { get; set; }
        public int IdPersonaCliente { get; set; }
        public int IdEtapa { get; set; }
        public string Observacion { get; set; }
        public int IdComponente { get; set; }
        public int IdFallo { get; set; }
        public int IdCausa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual CAUSAS CAUSAS { get; set; }
        public virtual COMPONENTES COMPONENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTE> COMPROBANTE { get; set; }
        public virtual ETAPAS ETAPAS { get; set; }
        public virtual FALLOS FALLOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONITOREO> MONITOREO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual PERSONA PERSONA1 { get; set; }
        public virtual PERSONA PERSONA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANEACION> PLANEACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIBO> RECIBO { get; set; }
    }
}
