'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ETAPAS
    Public Property IdEtapa As Integer
    Public Property Etapa As String

    Public Overridable Property PLANEACION As ICollection(Of PLANEACION) = New HashSet(Of PLANEACION)
    Public Overridable Property SERVICIOS As ICollection(Of SERVICIOS) = New HashSet(Of SERVICIOS)

End Class
