'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FALLOS
    Public Property IdFallo As Integer
    Public Property Fallo As String
    Public Property FechaCreacion As Date
    Public Property IdPersonaCreaciones As Integer
    Public Property Observaciones As String

    Public Overridable Property PERSONA As PERSONA
    Public Overridable Property SERVICIOS As ICollection(Of SERVICIOS) = New HashSet(Of SERVICIOS)

End Class
