'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GasNaturalEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GasNaturalEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CAUSAS() As DbSet(Of CAUSAS)
    Public Overridable Property COMPONENTES() As DbSet(Of COMPONENTES)
    Public Overridable Property COMPROBANTE() As DbSet(Of COMPROBANTE)
    Public Overridable Property ETAPAS() As DbSet(Of ETAPAS)
    Public Overridable Property FALLOS() As DbSet(Of FALLOS)
    Public Overridable Property MONITOREO() As DbSet(Of MONITOREO)
    Public Overridable Property PERSONA() As DbSet(Of PERSONA)
    Public Overridable Property PLANEACION() As DbSet(Of PLANEACION)
    Public Overridable Property RECIBO() As DbSet(Of RECIBO)
    Public Overridable Property RECORRIDO() As DbSet(Of RECORRIDO)
    Public Overridable Property SERVICIOS() As DbSet(Of SERVICIOS)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)

End Class
