'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERSONA
    Public Property IdPersona As Integer
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property FechaNacimiento As Date
    Public Property Telefono As Integer
    Public Property Direccion As String
    Public Property Email As String
    Public Property Ciudad As String
    Public Property Login As String
    Public Property Contraseña As String

    Public Overridable Property CAUSAS As ICollection(Of CAUSAS) = New HashSet(Of CAUSAS)
    Public Overridable Property COMPONENTES As ICollection(Of COMPONENTES) = New HashSet(Of COMPONENTES)
    Public Overridable Property FALLOS As ICollection(Of FALLOS) = New HashSet(Of FALLOS)
    Public Overridable Property PLANEACION As ICollection(Of PLANEACION) = New HashSet(Of PLANEACION)
    Public Overridable Property PLANEACION1 As ICollection(Of PLANEACION) = New HashSet(Of PLANEACION)
    Public Overridable Property SERVICIOS As ICollection(Of SERVICIOS) = New HashSet(Of SERVICIOS)
    Public Overridable Property SERVICIOS1 As ICollection(Of SERVICIOS) = New HashSet(Of SERVICIOS)
    Public Overridable Property SERVICIOS2 As ICollection(Of SERVICIOS) = New HashSet(Of SERVICIOS)

End Class
