'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLANEACION
    Public Property IdPlaneacion As Integer
    Public Property IdServicio As Integer
    Public Property FechaCreacion As Date
    Public Property IdPersonaCreacion As Integer
    Public Property IdPersonaModificacion As Integer
    Public Property IdEtapa As Integer
    Public Property FechaAsignacion As Date

    Public Overridable Property ETAPAS As ETAPAS
    Public Overridable Property PERSONA As PERSONA
    Public Overridable Property PERSONA1 As PERSONA
    Public Overridable Property SERVICIOS As SERVICIOS

End Class
