'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RECORRIDO
    Public Property IdRecorrido As Integer
    Public Property IdMonitoreo As Integer
    Public Property FechaRecorrido As Date
    Public Property Longitud As Integer
    Public Property Latitud As Integer
    Public Property Velocidad As Integer
    Public Property DistanciaRecorrida As Decimal

    Public Overridable Property MONITOREO As MONITOREO

End Class
