'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SERVICIOS
    Public Property IdServicio As Integer
    Public Property IdPersonaTecnico As Integer
    Public Property IdPersonaCreacion As Integer
    Public Property IdPersonaCliente As Integer
    Public Property IdEtapa As Integer
    Public Property Observacion As String
    Public Property IdComponente As Integer
    Public Property IdFallo As Integer
    Public Property IdCausa As Integer
    Public Property FechaCreacion As Date
    Public Property FechaModificacion As Date
    Public Property Direccion As String
    Public Property FechaAsignacion As Date

    Public Overridable Property CAUSAS As CAUSAS
    Public Overridable Property COMPONENTES As COMPONENTES
    Public Overridable Property COMPROBANTE As ICollection(Of COMPROBANTE) = New HashSet(Of COMPROBANTE)
    Public Overridable Property ETAPAS As ETAPAS
    Public Overridable Property FALLOS As FALLOS
    Public Overridable Property MONITOREO As ICollection(Of MONITOREO) = New HashSet(Of MONITOREO)
    Public Overridable Property PERSONA As PERSONA
    Public Overridable Property PERSONA1 As PERSONA
    Public Overridable Property PERSONA2 As PERSONA
    Public Overridable Property PLANEACION As ICollection(Of PLANEACION) = New HashSet(Of PLANEACION)
    Public Overridable Property RECIBO As ICollection(Of RECIBO) = New HashSet(Of RECIBO)

End Class
